parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):n&&(this[n]=l)}if(parcelRequire=f,i)throw i;return f}({"2tnM":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react");const t=(0,e.createContext)(["green",()=>{}]);var r=t;exports.default=r;
},{}],"/HkA":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=a;var e=require("react");const t={};function a(a){const[s,n]=(0,e.useState)([]),[o,r]=(0,e.useState)("unloaded");return(0,e.useEffect)(()=>{a?t[a]?n(t[a]):async function(){n([]),r("loading");const e=await fetch(`http://pets-v2.dev-apis.com/breeds?animal=${a}`),s=await e.json();t[a]=s.breeds||[],n(t[a]),r("loaded")}():n([])},[a]),[s,o]}
},{}],"qepC":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react-router-dom"),t=require("react/jsx-runtime");const r=({name:r,animal:s,breed:a,images:i,location:l,id:o})=>{let n="http://pets-images.dev-apis.com/pets/none.jpg";return i.length&&(n=i[0]),(0,t.jsxs)(e.Link,{to:`/details/${o}`,className:"relative block",children:[(0,t.jsx)("div",{children:(0,t.jsx)("img",{src:n,alt:r})}),(0,t.jsxs)("div",{className:"absolute bottom-0 left-0 bg-gradient-to-tr from-white to-transparent pr-2 pt-2",children:[(0,t.jsx)("h1",{children:r}),(0,t.jsx)("h2",{children:`${s} - ${a} - ${l}`})]})]})};var s=r;exports.default=s;
},{}],"r5l1":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=s(require("./Pet")),r=require("react/jsx-runtime");function s(e){return e&&e.__esModule?e:{default:e}}const t=({pets:s})=>(0,r.jsx)("div",{className:"grid gap-4 grid-cols-1 sm:grid-cols-2 lg:grid-cols-3",children:s.length?s.map(s=>(0,r.jsx)(e.default,{animal:s.animal,name:s.name,breed:s.breed,images:s.images,location:`${s.city}, ${s.state}`,id:s.id},s.id)):(0,r.jsx)("h2",{children:"No pets founds"})});var i=t;exports.default=i;
},{"./Pet":"qepC"}],"n0tu":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react"),a=r(require("./ThemeContext")),t=r(require("./useBreedList")),l=r(require("./Results")),s=require("react/jsx-runtime");function r(e){return e&&e.__esModule?e:{default:e}}const o=["bird","cat","dog","rabbit","reptile"],i=()=>{const[r,i]=(0,e.useState)(""),[n,u]=(0,e.useState)(""),[c,d]=(0,e.useState)(""),[h,m]=(0,e.useState)([]),[x]=(0,t.default)(r),[p,v]=(0,e.useContext)(a.default);async function b(){const e=await fetch(`http://pets-v2.dev-apis.com/pets?animal=${r}&location=${n}&breed=${c}`),a=await e.json();m(a.pets)}return(0,e.useEffect)(()=>{b()},[]),(0,s.jsxs)("div",{className:"my-0 mx-auto w-11/12",children:[(0,s.jsxs)("form",{className:"p-10 mb-10 rounded-lg bg-gray-200 shadow-lg flex flex-col justify-center items-center divide-y divide-gray-900",onSubmit:e=>{e.preventDefault(),b()},children:[(0,s.jsxs)("label",{className:"search-label",htmlFor:"location",children:["Location",(0,s.jsx)("input",{className:"w-60",type:"text",id:"location",value:n,placeholder:"Location",onChange:e=>u(e.target.value)})]}),(0,s.jsxs)("label",{className:"search-label",htmlFor:"animal",children:["Animal",(0,s.jsxs)("select",{className:"w-60",id:"animal",value:r,onChange:e=>i(e.target.value),onBlur:e=>i(e.target.value),children:[(0,s.jsx)("option",{}),o.map(e=>(0,s.jsx)("option",{value:e,children:e},e))]})]}),(0,s.jsxs)("label",{className:"search-label",htmlFor:"breed",children:["Breed",(0,s.jsxs)("select",{className:"w-60 disabled:opacity-50",disabled:!x.length,id:"breed",value:c,onChange:e=>d(e.target.value),onBlur:e=>d(e.target.value),children:[(0,s.jsx)("option",{}),x.map(e=>(0,s.jsx)("option",{value:e,children:e},e))]})]}),(0,s.jsxs)("label",{className:"search-label",htmlFor:"theme",children:["Theme",(0,s.jsxs)("select",{className:"w-60",value:p,onChange:e=>v(e.target.value),onBlur:e=>v(e.target.value),children:[(0,s.jsx)("option",{value:"peru",children:"Peru"}),(0,s.jsx)("option",{value:"darkblue",children:"Dark Blue"}),(0,s.jsx)("option",{value:"chartreuse",children:"Chartreuse"}),(0,s.jsx)("option",{value:"mediumorchid",children:"Medium Orchid"})]})]}),(0,s.jsx)("button",{className:"rounded px-6 py-2 color text-white hover:opacity-50 border-none",style:{backgroundColor:p},children:"Submit"})]}),(0,s.jsx)(l.default,{pets:h})]})};var n=i;exports.default=n;
},{"./ThemeContext":"2tnM","./useBreedList":"/HkA","./Results":"r5l1"}],"Ztkr":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react"),t=require("react/jsx-runtime");function a(e,t,a){return t in e?Object.defineProperty(e,t,{value:a,enumerable:!0,configurable:!0,writable:!0}):e[t]=a,e}class s extends e.Component{constructor(...e){super(...e),a(this,"state",{active:0}),a(this,"handleIdxClick",e=>{this.setState({active:+e.target.dataset.index})})}render(){const{active:e}=this.state,{images:a}=this.props;return(0,t.jsxs)("div",{className:"carousel",children:[(0,t.jsx)("img",{src:a[e],alt:"animal"}),(0,t.jsx)("div",{className:"carousel-smaller",children:a.map((a,s)=>(0,t.jsx)("img",{"data-index":s,onClick:this.handleIdxClick,src:a,className:s===e?"active":"",alt:"animal thumbnail"},a))})]})}}a(s,"defaultProps",{images:["http://pets-images.dev-apis.com/pets/none.jpg"]});var i=s;exports.default=i;
},{}],"mD05":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react"),r=require("react-router-dom"),t=require("react/jsx-runtime");function o(e,r,t){return r in e?Object.defineProperty(e,r,{value:t,enumerable:!0,configurable:!0,writable:!0}):e[r]=t,e}class s extends e.Component{constructor(...e){super(...e),o(this,"state",{hasError:!1})}static getDerivedStateFromError(){return{hasError:!0,redirect:!1}}componentDidCatch(e,r){console.error("ErrorBoundary caught an error",e,r)}componentDidUpdate(){this.state.hasError&&setTimeout(()=>this.setState({redirect:!0}),5e3)}render(){return this.state.redirect?(0,t.jsx)(r.Redirect,{to:"/"}):this.state.hasError?(0,t.jsxs)("h2",{children:["There was an error with this listing. ",(0,t.jsx)(r.Link,{to:"/",children:"Click here"})," ","to back to the home page or wait five seconds."]}):this.props.children}}var i=s;exports.default=i;
},{}],"KnKP":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react"),r=require("react-dom"),t=require("react/jsx-runtime");let u;const c=({children:c})=>{u=u||document.getElementById("modal");const n=(0,e.useRef)(null);return n.current||(n.current=document.createElement("div")),(0,e.useEffect)(()=>(u.appendChild(n.current),()=>u.removeChild(n.current)),[]),(0,r.createPortal)((0,t.jsx)("div",{children:c}),n.current)};var n=c;exports.default=n;
},{}],"C/Dc":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=u;var e=require("react"),t=require("react-router-dom"),s=a(require("./Carousel")),i=a(require("./ThemeContext")),r=a(require("./ErrorBoundary")),o=a(require("./Modal")),n=require("react/jsx-runtime");function a(e){return e&&e.__esModule?e:{default:e}}function d(e,t,s){return t in e?Object.defineProperty(e,t,{value:s,enumerable:!0,configurable:!0,writable:!0}):e[t]=s,e}class l extends e.Component{constructor(...e){super(...e),d(this,"state",{loading:!0,showModal:!1}),d(this,"toggleModal",()=>this.setState({showModal:!this.state.showModal})),d(this,"adopt",()=>window.location="http://bit.ly/pet-adopt")}async componentDidMount(){const e=await fetch(`http://pets-v2.dev-apis.com/pets?id=${this.props.match.params.id}`),t=await e.json();this.setState(Object.assign({loading:!1},t.pets[0]))}render(){if(this.state.loading)return(0,n.jsx)("h2",{children:"loading..."});const{animal:e,breed:t,city:r,state:a,description:d,name:l,images:c,showModal:u}=this.state;return(0,n.jsxs)("div",{className:"details",children:[(0,n.jsx)(s.default,{images:c}),(0,n.jsxs)("div",{children:[(0,n.jsx)("h1",{children:l}),(0,n.jsxs)("h2",{children:[e," - ",t," - ",r,", ",a]}),(0,n.jsx)(i.default.Consumer,{children:([e])=>(0,n.jsxs)("button",{onClick:this.toggleModal,style:{backgroundColor:e},children:["Adopt ",l]})}),(0,n.jsx)("p",{children:d}),u?(0,n.jsx)(o.default,{children:(0,n.jsxs)("div",{children:[(0,n.jsxs)("h1",{children:["Would you like to adopt ",l,"?"]}),(0,n.jsxs)("div",{className:"buttons",children:[(0,n.jsx)("button",{onClick:this.adopt,children:"Yes"}),(0,n.jsx)("button",{onClick:this.toggleModal,children:"No"})]})]})}):null]})]})}}const c=(0,t.withRouter)(l);function u(){return(0,n.jsx)(r.default,{children:(0,n.jsx)(c,{})})}
},{"./Carousel":"Ztkr","./ThemeContext":"2tnM","./ErrorBoundary":"mD05","./Modal":"KnKP"}],"eBcb":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react"),r=require("react-router-dom"),t=l(require("./SearchParams")),s=l(require("./Details")),a=l(require("./ThemeContext")),i=require("react/jsx-runtime");function l(e){return e&&e.__esModule?e:{default:e}}const d=()=>{const l=(0,e.useState)("darkblue");return(0,i.jsx)(e.StrictMode,{children:(0,i.jsx)(a.default.Provider,{value:l,children:(0,i.jsxs)("div",{className:"p-0 m-0",style:{background:"url(http://pets-images.dev-apis.com/pets/wallpaperA.jpg)"},children:[(0,i.jsx)("header",{className:"w-full mb-10 text-center p-7 bg-gradient-to-b from-purple-400 via-pink-400 to-red-500",children:(0,i.jsx)(r.Link,{to:"/",className:"text-6xl text-white hover:text-gray-200",children:(0,i.jsx)("h1",{children:"Adopt Me!"})})}),(0,i.jsxs)(r.Switch,{children:[(0,i.jsx)(r.Route,{path:"/details/:id",children:(0,i.jsx)(s.default,{})}),(0,i.jsx)(r.Route,{path:"/",children:(0,i.jsx)(t.default,{})})]})]})})})};var u=d;exports.default=u;
},{"./SearchParams":"n0tu","./Details":"C/Dc","./ThemeContext":"2tnM"}],"Focm":[function(require,module,exports) {
"use strict";var e=u(require("express")),t=require("react-dom/server"),r=require("react-router-dom"),s=u(require("fs")),i=u(require("../src/App")),n=require("react/jsx-runtime");function u(e){return e&&e.__esModule?e:{default:e}}const d=process.env.PORT||3e3,o=s.default.readFileSync("dist/index.html").toString(),l=o.split("not rendered"),c=(0,e.default)();c.use("/dist",e.default.static("dist")),c.use((e,s)=>{s.write(l[0]);const u={},d=(0,n.jsx)(r.StaticRouter,{url:e.url,context:u,children:(0,n.jsx)(i.default,{})}),o=(0,t.renderToNodeStream)(d);o.pipe(s,{end:!1}),o.on("end",()=>{s.status(u||200),s.write(l[1]),s.end()})}),console.log(`listening on http://localhost:${d}`),c.listen(d);
},{"../src/App":"eBcb"}]},{},["Focm"], null)
//# sourceMappingURL=/index.js.map